import { Task } from "./types";

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Implement login page",
    dueDate: "2026-04-01",
    completed: true,
    category: "frontend",
    priority: "high",
  },
  {
    id: "2",
    title: "Design dashboard layout",
    dueDate: "2026-04-03",
    completed: true,
    category: "frontend",
    priority: "medium",
  },
  {
    id: "3",
    title: "Set up REST API endpoints",
    dueDate: "2026-04-05",
    completed: false,
    category: "backend",
    priority: "high",
  },
  {
    id: "4",
    title: "Configure CI/CD pipeline",
    dueDate: "2026-04-07",
    completed: true,
    category: "devops",
    priority: "high",
  },
  {
    id: "5",
    title: "Add unit tests for auth module",
    dueDate: "2026-04-09",
    completed: false,
    category: "backend",
    priority: "medium",
  },
  {
    id: "6",
    title: "Create user profile component",
    dueDate: "2026-04-11",
    completed: false,
    category: "frontend",
    priority: "low",
  },
  {
    id: "7",
    title: "Set up monitoring alerts",
    dueDate: "2026-04-13",
    completed: false,
    category: "devops",
    priority: "medium",
  },
  {
    id: "8",
    title: "Implement search functionality",
    dueDate: "2026-04-15",
    completed: false,
    category: "frontend",
    priority: "high",
  },
  {
    id: "9",
    title: "Database migration script",
    dueDate: "2026-04-17",
    completed: true,
    category: "backend",
    priority: "high",
  },
  {
    id: "10",
    title: "Write API documentation",
    dueDate: "2026-04-19",
    completed: false,
    category: "backend",
    priority: "low",
  },
  {
    id: "11",
    title: "Set up staging environment",
    dueDate: "2026-04-21",
    completed: false,
    category: "devops",
    priority: "medium",
  },
  {
    id: "12",
    title: "Responsive design fixes",
    dueDate: "2026-04-23",
    completed: false,
    category: "frontend",
    priority: "medium",
  },
];
